#!/bin/bash

# Permissions: Make sure that chmod +x script has been executed
# Usage: ./script

cd /home/fabio/source/transitioning-to-kx-products || { echo "Failed to change directory"; exit 1; }

source .venv/bin/activate || { echo "Failed to activate virtual environment"; exit 1; }

python -m bid_ask_spread.bid_ask_spread_script /home/fabio/data/IBM_trades.csv /home/fabio/data/IBM_quotes.csv || { echo "Python script failed"; exit 1; }

echo "Script completed successfully."

exit 0